'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__proxy__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,
getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";var __name__="registers";export var Register=__class__("Register",[object],{__module__:__name__,get __init__(){return __get__(this,function(self,val){self.val=val})},get __repr__(){return __get__(this,function(self){return str(self.val)})},get value(){return __get__(this,
function(self){return self.val})},get assign(){return __get__(this,function(self,val){if(py_typeof(val)==int){if(val>9999)var val=9999;if(val<-9999)var val=-9999}self.val=val})}});export var File=__class__("File",[Register],{__module__:__name__,get __init__(){return __get__(this,function(self,data,id,host){self.data=data;self.id=id;self.host=host;self.index=0})},get __repr__(){return __get__(this,function(self){return str(self.id)})},get reprlong(){return __get__(this,function(self){var data=function(){var __accu0__=
[];for(var e of self.data)__accu0__.append(e);return __accu0__}()+[" "];var i=[];for(var e of data)i.append(str(e));for(var e=0;e<len(i);e++)if(e==self.index)i[e]="\u001b[4m\u001b[1m"+i[e]+"\u001b[0m";return", ".join(i)})},get value(){return __get__(this,function(self){try{var v=self.data[self.index]}catch(__except0__){if(isinstance(__except0__,IndexError)){var __except1__=Exception("FILE ACCESS OUT OF RANGE");__except1__.__cause__=null;throw __except1__;}else throw __except0__;}self.index++;return v})},
get assign(){return __get__(this,function(self,val){if(py_typeof(val)==int){if(val>9999)var val=9999;if(val<-9999)var val=-9999}if(self.index==len(self.data))self.data.append(val);else self.data[self.index]=val;self.index++})},get seek(){return __get__(this,function(self,index){self.index+=index;if(self.index>len(self.data))self.index=len(self.data);if(self.index<0)self.index=0})},get void(){return __get__(this,function(self){try{self.data.py_pop(self.index)}catch(__except0__){if(isinstance(__except0__,
IndexError)){var __except1__=Exception("FILE ACCESS OUT OF RANGE");__except1__.__cause__=null;throw __except1__;}else throw __except0__;}})},get wipe(){return __get__(this,function(self){self.data=[];self.index=0})},get eof(){return __get__(this,function(self){return self.index==len(self.data)})},get link(){return __get__(this,function(self,host){self.host=host})}});export var Communication=__class__("Communication",[Register],{__module__:__name__,get __init__(){return __get__(this,function(self,
scope,parent){self.scope=scope;self.parent=parent;self.val=null})},get __repr__(){return __get__(this,function(self){return str(self.val)})},get value(){return __get__(this,function(self){if(self.scope=="GLOBAL")var scope="GLOBAL";else var scope=parent.host;level.m[scope].reading=true;if(level.m[scope].writing){level.m[scope].writing=false;return level.m[scope].val}else{parent.cycle++;return self.value()}})},get assign(){return __get__(this,function(self,val){if(self.scope=="GLOBAL")var scope="GLOBAL";
else var scope=parent.host;level.m[scope].writing=true;if(level.m[scope].reading){level.m[scope].reading=false;level.m[scope].val=val}else{parent.cycle++;self.assign(val)}})},get mode(){return __get__(this,function(self){if(self.mode=="GLOBAL")self.mode="LOCAL";else self.mode="GLOBAL"})},get mrd(){return __get__(this,function(self){if(self.scope=="GLOBAL")var scope="GLOBAL";else var scope=parent.host;return level.m[scope].writing})}});

//# sourceMappingURL=registers.map